name: publish (nuget)

on:
  workflow_call:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write # allow GITHUB_TOKEN to publish packages
    strategy:
      fail-fast: false
      matrix:
        source: [github, nuget]
        prefix: ['', '${{ github.repository_owner }}.']
        include:
          - source: github
            registry: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            username: ${{ github.repository_owner }}
            token: GH_PUBLISH_TOKEN
          - source: nuget
            registry: https://api.nuget.org/v3/index.json
            username: ${{ github.repository_owner }}
            token: NUGET_ORG_TOKEN
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        systems: |
          python
          dotnet
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.com
    - uses: kagekirin/gha-py-toolbox/actions/gclient/setup@main
      with:
        path: ../depot_tools
    - id: install-unity
      uses: kagekirin/gha-py-toolbox/actions/unity/direct-setup@main
      with:
        version: ${{ vars.UNITY_VERSION }}
        changeset: ${{ vars.UNITY_CHANGESET }}
        components: ${{ vars.UNITY_COMPONENTS }}
        unity-path: ../unity

    - uses: kagekirin/Unity.Mathematics.NuGet/gha/jobs/publish-with-overlay@main
      with:
        registry: ${{ matrix.registry }}
        nuget-token: ${{ secrets[matrix.token] }}
        lfs: true
        token: ${{ secrets.GH_READONLY_TOKEN }}
        persist-credentials: true
        configurations: Release
        frameworks: netstandard2.1
        projects: Unity.Mathematics.sln
        nuget-cache: ${{github.workspace}}/.packages
        build-cache: ${{github.workspace}}/.artifacts
        restore-options: ''
        build-options: ''
        pack-options: ''
        publish-options:
        filter-packages: |-
          ^(\.artifacts).*$
      env:
        GH_NUGET_USER: ${{ github.actor }}
        GH_NUGET_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
        UNITY_ASSEMBLY_PATH: ${{steps.install-unity.outputs.editor-path}}/Data/Managed
        PACKAGE_PREFIX: ${{ matrix.prefix }}
